#!/bin/bash
DIR="apostrophe-test"
MYDIR='node_modules/custom-code-editor'

copy_module (){
    if [ "$(ls -A $MYDIR && du $MYDIR)" ];then
        echo "$MYDIR file already created"
    else
        mkdir "$MYDIR"
    fi
    cp -r ../lib "$MYDIR"
    cp -r ../views "$MYDIR"
    cp -r ../public "$MYDIR"
    cp ../index.js "$MYDIR"
    cp ../package.json "$MYDIR"
    echo "Your custom-code-editor copied to $MYDIR"
}

# Checking Apostrophe CLI installed in a system
if [ "$(apostrophe --version)" ];then
    echo "Apostrophe CLI existed"
    printf "*************************\n\n"
else
    echo "Installing Apostrophe CLI"
    npm i apostrophe-cli -g
    printf "*************************\n\n"
fi
# init
# Look for apostrophe-test directory
# script $(ls -A $DIR) checking directory
# script $(du $DIR) check file size existed
if [ "$(ls -A $DIR && du $DIR)" ];then
    echo "apostrophe-test folder already existed"
    printf "\n\nCopy app.js to testing directory\n"
    printf "*******************************\n"
    cp -v tests/apos/app.js /apostrophe-test &&
    printf "*******************************\n\n"
    cd apostrophe-test
    printf "Re-installed Packaged to keep updated \n"
    npm install
    printf "\nPackage Installed."
    echo "Copy our module to $PWD inside node_modules to test"
    copy_module
    cd ..
else
    echo "Creating apostrophe-test folder"
    apostrophe create-project apostrophe-test
    printf "\n\nCopy app.js to testing directory\n"
    printf "*******************************\n"
    cp -v tests/apos/app.js apostrophe-test &&
    printf "*******************************\n\n"
    cd apostrophe-test
    echo "Entering current directory $PWD"
    echo "Apostrophe Boilerplate created"
    npm install
    printf "Copy our module to $PWD inside node_modules to test\n\n"
    copy_module
    cd ..
fi

# Running Test
echo "** running test from"
echo $PWD
./node_modules/.bin/nightwatch tests/scenarios/* --config nightwatch.js --env=local &&
echo "TEST ENDED"